---
- name: this playbook installs minishift in a EL/7 host
  hosts: localhost
  become: True
  pre_tasks:
    - name: Ensure needed packages are installed
      yum: name={{ item }} state='latest' update_cache='yes'
      with_items:
        - libselinux-python
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version >= 7"
      tags:
        - pre_tasks
  roles:
    - { role: install-minishift, when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version >= 7" }
