---
# tasks file for install-minishift

- name: "Download and unarchive minishift"
  unarchive: >
    src="{{ item }}"
    dest="/tmp"
    remote_src="yes"
  with_items:
    - "{{ minishift_installer_package_url }}"

- name: "ensure minishift binary is installed"
  copy: >
    src="/tmp/{{ item }}"
    dest="/usr/local/bin/{{ item | basename }}"
    owner="root"
    group="root"
    mode="755"
  with_items: 
    - "{{ minishift_binary }}"

