---
# tasks file for install-minishift

- name: ensure kvm driver is downloaded and installed
  become: True
  shell: "wget {{ driver_kvm_binary_url }} "
  args:
    chdir: /usr/local/bin/
    creates: /usr/local/bin/{{ driver_kvm_binary_url | basename}}

- name: ensure perms in kvm driver
  become: True
  file: >
    path="/usr/local/bin/{{ driver_kvm_binary_url | basename}}"
    owner="root"
    group="libvirt"
    mode="0755"

- name: "ensure minishift tarball is downloaded"
  become: True
  shell: "wget {{ minishift_installer_package_url }}"
  args:
    chdir: /tmp
    creates: /tmp/{{ minishift_installer_package_url | basename}}

- name: "ensure minishift tarball is unarchived"
  become: True
  unarchive: >
    src="/tmp/{{ minishift_installer_package_url | basename }}"
    dest="/tmp"
    
- name: "ensure minishift binary is installed"
  become: True
  copy: >
    src="/tmp/minishift-1.11.0-linux-amd64/minishift"
    dest="/usr/local/bin/minishift"
    owner="root"
    group="libvirt"
    mode="755"
