---
# tasks file for install-minishift

- name: "copy minishift tarball"
  copy: >
    src="{{ minishift_installer_package }}"
    dest="/tmp"
    owner="root"
    group="root"
    mode="755"

- name: download some_service_def init.d script
  get_url: >
    url="{{ minishift_installer_package_url }}"
    dest="/tmp"
    owner="root"
    group="root"
    mode="755"
    
- name: "ensure minishift tarball is unarchived"
  unarchive: >
    src="/tmp/{{ item }}"
    dest="/tmp"
    remote_src="yes"
  with_items:
    - "{{ minishift_installer_package }}"

- name: "ensure minishift binary is installed"
  copy: >
    src="/tmp/{{ item }}"
    dest="/usr/local/bin/{{ item | basename }}"
    owner="root"
    group="root"
    mode="755"
  with_items: 
    - "{{ minishift_binary }}"
