---
# tasks file for install-minishift

# install kvm driver 
- name: ensure kvm driver is downloaded and installed
  get_url: >
    url="{{ item }}"
    dest="/usr/local/bin/{{item | basename}}"
    owner="root"
    group="root"
    mode="0755"
  with_items:
    - "{{ driver_kvm_binary }}"


- name: install pre-requisite packages to unarchive compresed files
  yum: >
    name="{{item}}"
    state="present"
  with_items:
    - tar
    - unzip
