---
# tasks file for install-minishift
- name: ensure pre-requisite packages are installed
  become: True
  yum: >
    name="{{item}}"
    state="present"
  with_items: "{{ prerequisite_packages }}"

- name: install pre-requisite packages to unarchive compresed files
  become: True
  yum: >
    name="{{item}}"
    state="present"
  with_items:
    - tar
    - unzip
    

