---
# defaults file for install-minishift

prerequisite_packages: 
  - qemu-kvm
  - libvirt

minishift_binary: "minishift-1.11.0-linux-amd64/minishift"
minishift_installer_package: "minishift-1.11.0-linux-amd64.tgz"
minishift_installer_package_url: https://github.com/minishift/minishift/releases/download/v1.11.0/minishift-1.11.0-linux-amd64.tgz

driver_kvm_binary_url: "https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm"



